### ISSUE TITLE
Project overview & Documentation

### ISSUE THREAD

**Issue by surajgupta-git** [airavata-courses/PixelGram#1]

**Comment by surajgupta-git** [comment]
Application overview: 
The Application "Complain it" targets the residents of a community who can raise concerns regarding maintenance, repairs, and damages in the community.
Acknowledgment from community management
upload ....download .....
the resident can provide access/share 
All the residents will be required to set up login credentials for authentication.
status tracking  
community updates/notifications
chatting

**Comment by sravya160597** [comment]
The application "Complain it" targets the residents of a community which enables them to raise concerns regarding maintenance, repairs and damages in their apartments or at common areas of the community. The complaints are carried forward to the management of the community. All the residents are required to set up login credentials for authentication. The user data is securely stored in the cloud. This app allows residents to register their complaints by uploading a picture followed by 
it's description. The users have an option to download the images and The management further has the option to 
download the pictures in order to solve them and in return can upload the image after fixing the issue. The residents have 
the access to share the images in other social media platforms as well. The user can track their complaint status, give rating and 
feedback to the assigned technician. There is also a chat box where the assigned technician will be able to instantly talk
to the resident about any extra information required. The residents will be able to get community updates and notifications 
if any one posts a concern about the common areas in the community.

**Comment by surajgupta-git** [comment]
@sravya160597 Adding few modifications and changing the order of few sentences.

The application "Complain it" targets the residents of a community which enables them to raise concerns regarding maintenance, repairs, and damages in their apartments or in common areas of the community. This app allows residents to register their complaints by uploading a picture followed by its description. The complaints are carried forward to the management of the community and the management in return after resolving their concerns acknowledges the residents by uploading images of the fixed issue. All these images and user data are securely stored in the cloud and are available for download when required. These images can be shared on other social media platforms as well. All the residents are required to set up their login credentials to be recognized as authenticated users which provides additional security and privacy to the users. The user can track their complaint status, give ratings to the assigned technician, and feedback to the complaint resolution. There is also a chat box where the assigned technician/management will be able to instantly talk to the resident about any extra information required. The residents will be able to get community updates and notifications if anyone posts a concern about the common areas in the community.

**Comment by sannidhi09** [comment]
I have one concern which is regarding the ratings/feedback to the assigned technician might deviate things from the mainline. As we are focusing on solving the resident's concerns through management I think it's better if we provide residents/users with black-white data, anyway, we are notifying real-time updates on the complaint.

**Comment by surajgupta-git** [comment]
Agreed @sannidhi09 lets remove that thing now and think about in the future.
Lets write The user can track the status of their complaint with real-time updates.

**Comment by surajgupta-git** [comment]
PixelGram is a Modern-age application created for the Millennials to save their precious moments and memories securely online without the need of storing hard photocopies. one can log in to this application through any of their Google, Github, or IU user accounts. This application automatically backups the photos from the device or the user can manually upload photos of their interest. This application helps people share their photos and albums with individuals privately or with a group of individuals. The photos can be manually categorized into albums or are organized automatically based on date, location, or faces. The photos are stored in the cloud and can be retrieved from offline systems when and as required.

**Comment by sravya160597** [comment]
Having access to camera 24/7 has its benefits. Everything can be captured. The downside is, how can we store all these images
and share them?  Our photo sharing app PixelGram makes it the best way to store photos when you use multiple objects to photograph. PixelGram allows bulk upload of images and saving them securely. The users can login through their google, IU or Git hub credentials. This app allows the users to organize and tag their images with names and locations for searchability ease. The images stored by the user can be grouped on a timeline and can be placed in albums. The users can further share the images or albums privately or with a group of individuals. The photos are stored in the cloud and can be retrieved from offline systems as and when required. With PixelGram It's easier and quicker to efficiently store your captured moments.

**Comment by sannidhi09** [comment]
> PixelGram is a Modern-age application created for the Millennials to save their precious moments and memories securely online without the need of storing hard photocopies. one can log in to this application through any of their Google, Github, or IU user accounts. This application automatically backups the photos from the device or the user can manually upload photos of their interest. This application helps people share their photos and albums with individuals privately or with a group of individuals. The photos can be manually categorized into albums or are organized automatically based on date, location, or faces. The photos are stored in the cloud and can be retrieved from offline systems when and as required.

Are we planning to automatically sync images from a device and categorize them based on people's faces, I think we have fewer data points to do so.

**Comment by surajgupta-git** [comment]
@sannidhi09  you are right. let's do this,
" This app allows the users to organize and tag their images with names and locations for searchability ease."
Automatic categorization may not be possible.

**Comment by sravya160597** [comment]
> > PixelGram is a Modern-age application created for the Millennials to save their precious moments and memories securely online without the need of storing hard photocopies. one can log in to this application through any of their Google, Github, or IU user accounts. This application automatically backups the photos from the device or the user can manually upload photos of their interest. This application helps people share their photos and albums with individuals privately or with a group of individuals. The photos can be manually categorized into albums or are organized automatically based on date, location, or faces. The photos are stored in the cloud and can be retrieved from offline systems when and as required.
> 
> Are we planning to automatically sync images from a device and categorize them based on people's faces, I think we have fewer data points to do so.

Yes, categorization based on faces might not be possible right now. we will think about that option later .

**Comment by sannidhi09** [comment]
I think it would be better if people can share photos without login hassle as our project is based on photo sharing mainly. doing so we won't provide the categorization, image search, and storage for the long term.

**Comment by surajgupta-git** [comment]
we can consider this as an additional feature, so I think we can skip this for now in the application overview.

**Comment by sravya160597** [comment]
Having access to a camera 24/7 has its benefits. Everything can be captured. The downside is, how can we store all these images and share them? Our photo sharing application 'PixelGram" makes it the best way to store photos online when you use multiple devices to photograph. PixelGram allows bulk upload of images as well as supports automatic photo backup from various devices. The users can log in through their Google, IU, or GitHub credentials. This app allows the users to organize their photos into albums/folders and also tag their images with names and locations for searchability ease. The images stored by the user will be grouped on a timeline. The users can further share the images or albums privately or with a group of individuals. The photos are stored in the cloud and can be retrieved from offline systems as and when required. With PixelGram It's easier, safer, and quicker to efficiently store & share your captured moments online.
