### ISSUE TITLE
Milestone-2 Documentation

### ISSUE THREAD

**Issue by surajgupta-git** [airavata-courses/PixelGram#17]

**Comment by sravya160597** [comment]
PixelGram is a micro-service architecture-based application that enables users to upload, download, share and manage images. There is an end user who logins through the UI . The UI is built using react js  and bootstrap. The front end communicates with the backend architecture using the GRPC protocol. We are using envoy proxy mediator as the GRPC web client does not send HTTP2 requests, so we convert them into HTTP2 using envoy. The GRPC helps in the inter service communication and the communication between react client and microservices.
The different microservices the we are using are:
The upload/download image service which enables a user to upload the images to the cloud as well as download the images into the local.
The image service enables the user to share the image data to different PixelGram users.
The user service enables a user to register and login into the application for uploading, downloading and sharing the images. There are also 3Rd party login methods such as IU login, GitHub login and Google login 
The meta data service is present to get the meta data of an image like location, timestamp, file format, size etc.
The session management service is built to manage the session of user for better security after login.
The database service to connect to the data base and all the operations related to that.
All other services connect to database via this service

**Comment by sravya160597** [comment]
![flowchart](https://user-images.githubusercontent.com/29830913/108661175-2edd3780-7499-11eb-802d-515a67d5704c.jpg)
