### ISSUE TITLE
Information Architecture - Flowcharts

### ISSUE THREAD

**Issue by surajgupta-git** [airavata-courses/PixelGram#4]

**Comment by sannidhi09** [comment]
![Project (1)](https://user-images.githubusercontent.com/16603685/106818895-fccd7800-6646-11eb-8c9b-3eda1a456c75.png)

Flow chart draft.
Further suggestions are welcome !!

**Comment by surajgupta-git** [comment]
everything seems to be same as discussed over call, we can proceed with the commit in dev branch.
No modifications from my side.

**Comment by surajgupta-git** [comment]
[
![DataFlow](https://user-images.githubusercontent.com/66148226/106973152-49d14d00-6720-11eb-85e5-6f2810334fce.jpeg)
](url)

**Comment by sannidhi09** [comment]
![Project (2)](https://user-images.githubusercontent.com/16603685/106991686-c37b3200-6744-11eb-9624-e42554c92096.png)

Control Flow Chart.
