### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by hbondala** [airavata-courses/PixelGram#50]
After skimming through your repository I have found that, there is not support for building individual services. Please let me know if that's a valid concern or not.

**Comment by surajgupta-git** [comment]
Though we did not include information for building each service in its specific directory, we have included all the information of all services commonly in wiki -> milestone 2

**Comment by sannidhi09** [comment]
We are currently working on providing individual service deployments.

Thanks for your review.

**Comment by sannidhi09** [comment]
We have incorporated individual service building by creating separate branch for each service.
