### ISSUE TITLE
README file updates

### ISSUE THREAD

**Issue by surajgupta-git** [airavata-courses/PixelGram#7]
Application Name: PixelGram

User type: Millennials

Goal: As a user, I want to use this application to store all my captured moments and memories in the cloud and retrieve them as and when required. 

Actions :
1. The user should be able to upload and download their photos.
2. The user must be able to log in via various Authentication methods like Google, Github, and IU login.
3. All the photos are being stored in the cloud securely.
4. The user should be able to share their photos to other platforms like mail, Whatsapp, etc.
5. The user should be able to organize their photos into albums and also enable shared access (either private, group access, or public) to their albums.

**Comment by surajgupta-git** [comment]
[https://github.com/surajgupta-git](url)
[https://github.com/sravya160597](url)
[Sai Prudvi krishna Sannidhi](https://github.com/sannidhi09)

**Comment by sravya160597** [comment]
![final readme](https://user-images.githubusercontent.com/29830913/106408687-e20fbf00-640c-11eb-982e-2c5ea7c381d3.jpg)

**Comment by surajgupta-git** [comment]
![Napkin Diag](https://user-images.githubusercontent.com/66148226/106688289-d0105680-659b-11eb-9f1e-f5432a3ad4e2.jpg)
